import{a as u,S,i as n}from"./assets/vendor-Bt_EzQve.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function r(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(t){if(t.ep)return;t.ep=!0;const s=r(t);fetch(t.href,s)}})();u.defaults.baseURL="https://pixabay.com/api/";const P="52985657-6fa5448d905561c90358ed2ab";let c=1;const q=15;let d="";async function f(e){e!==d&&(d=e,c=1);const o={key:P,q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",page:c,per_page:q};try{const r=await u.get("/",{params:o});return c+=1,r.data}catch(r){throw console.log("❌ Помилка запиту до Pixabay API:",r),r}}function v(){c=1}function g(e){const o=document.querySelector(".js-gallery");if(!o){console.error("Gallery element .js-gallery not found.");return}const r=e.map(({webformatURL:l,largeImageURL:t,tags:s,likes:i,views:b,comments:L,downloads:w})=>`
        <li class="gallery-card">
          <a href="${t}">
            <img class="gallery-img" src="${l}" alt="${s}" loading="lazy" />
          </a>
          <ul class="info">
            <li><b>Likes:</b> ${i}</li>
            <li><b>Views:</b> ${b}</li>
            <li><b>Comments:</b> ${L}</li>
            <li><b>Downloads:</b> ${w}</li>
          </ul>
        </li>
      `).join("");o.insertAdjacentHTML("beforeend",r)}function M(){document.querySelector(".js-gallery").innerHTML=""}const a={form:document.querySelector(".js-form"),gallery:document.querySelector(".js-gallery"),loader:document.querySelector(".loader"),loadMoreBtn:document.querySelector(".js-load-more")};let h="";const j=15,y=new S(".js-gallery a",{captionsData:"alt",captionDelay:250});a.form.addEventListener("submit",B);a.loadMoreBtn.addEventListener("click",E);function m(){a.loader.classList.remove("hidden")}function p(){a.loader.classList.add("hidden")}function $(){const e=a.gallery.querySelectorAll(".gallery-card");if(e.length===0)return;const o=e[e.length-1],{height:r}=o.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}async function B(e){e.preventDefault();const o=e.target.elements.user_query.value.trim();if(!o){n.warning({title:"Oops!",message:"Please enter a search term.",position:"topRight"});return}M(),v(),h=o,a.loadMoreBtn.classList.add("hidden"),m();try{const r=await f(o);if(r.hits.length===0){n.info({title:"No results",message:"Sorry, there are no images matching your search query.",position:"topRight"});return}g(r.hits),y.refresh(),r.totalHits>j&&a.loadMoreBtn.classList.remove("hidden")}catch(r){n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(r)}finally{p()}}async function E(){m();try{const e=await f(h);if(e.hits.length===0){a.loadMoreBtn.classList.add("hidden"),n.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}g(e.hits),y.refresh(),$(),e.hits.length<15&&(a.loadMoreBtn.classList.add("hidden"),n.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(e){n.error({title:"Error",message:"Failed to load more images.",position:"topRight"}),console.error(e)}finally{p()}}
//# sourceMappingURL=index.js.map
